# Generated by Django 6.0.7 on 2026-07-14 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propietarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('localidad', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Casa', 'Casa'), ('Departamento', 'Departamento'), ('PH', 'PH'), ('Terreno', 'Terreno')], max_length=50)),
                ('ambientes', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Vendida', 'Vendida'), ('Alquilada', 'Alquilada')], max_length=50)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propietarios.propietario')),
            ],
        ),
    ]
